= Japanese Dates Quiz Practice

Leading up to a Japanese test, I created a "quiz generator" that would randomly generate a quiz for me to practice with. I would then take the quiz and grade myself. This was a great way to practice and study for the test. This project is pretty much a cleaned up and stylized version of that quiz generator.

== Technologies Used

This is fully written in *PURE* JavaScript, HTML, and CSS. No libraries or frameworks were used. The only thing that was used was the Google Fonts API to import the font used in the project.

※ _Please don't ask why, I thought it would be "easier" to do it this way. I was wrong._

== How to Use

Live version of the project can be found https://joshuabrest.github.io/japanese-dates-quiz-practice/[here].

If you want to run this locally, you can simply clone the repository and run a dev server in the `src` directory.

== Future Plans

None

== License

This project is licensed under the MIT License - see the LICENSE file for details.